'------------------------------------------------------------------------------
' <auto-generated>
'     Tento kód byl generován nástrojem.
'     Verze modulu runtime:4.0.30319.42000
'
'     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
'     dojde-li k novému generování kódu.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    'pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    'Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    's parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    '''<summary>
    '''  Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("GPXTrailAnalyzer.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        '''  vyhledání prostředků pomocí třídy prostředků se silnými typy.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bgImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bgImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property czech_flag() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("czech_flag", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property De_Flag() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("De_Flag", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property en_flag() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("en_flag", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pl_flag() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pl_flag", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledá lokalizovaný řetězec podobný {\rtf1\adeflang1025\ansi\ansicpg1250\uc1\adeff0\deff0\stshfdbch0\stshfloch44\stshfhich44\stshfbi44\deflang1029\deflangfe1029\themelang1029\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset238\fprq2{\*\panose 02020603050405020304}Times New Roman;}
        '''{\f2\fbidi \fmodern\fcharset238\fprq1{\*\panose 02070309020205020404}Courier New;}{\f10\fbidi \fnil\fcharset2\fprq2{\*\panose 05000000000000000000}Wingdings;}{\f34\fbidi \froman\fcharset238\fprq2{\*\panose 02040503050406030204}Cambria Math;}
        '''{\f42\fbi [zbytek řetězce byl zkrácen];.
        '''</summary>
        Friend ReadOnly Property Readme_cs() As String
            Get
                Return ResourceManager.GetString("Readme_cs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledá lokalizovaný řetězec podobný {\rtf1\adeflang1025\ansi\ansicpg1250\uc1\adeff31507\deff0\stshfdbch31506\stshfloch44\stshfhich44\stshfbi31507\deflang1029\deflangfe1029\themelang1029\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset238\fprq2{\*\panose 02020603050405020304}Times New Roman;}
        '''{\f2\fbidi \fmodern\fcharset238\fprq1{\*\panose 02070309020205020404}Courier New;}{\f10\fbidi \fnil\fcharset2\fprq2{\*\panose 05000000000000000000}Wingdings;}{\f34\fbidi \froman\fcharset238\fprq2{\*\panose 02040503050406030204}Cambria Math;} [zbytek řetězce byl zkrácen];.
        '''</summary>
        Friend ReadOnly Property Readme_de() As String
            Get
                Return ResourceManager.GetString("Readme_de", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledá lokalizovaný řetězec podobný {\rtf1\adeflang1025\ansi\ansicpg1250\uc1\adeff31507\deff0\stshfdbch31506\stshfloch44\stshfhich44\stshfbi31507\deflang1029\deflangfe1029\themelang1029\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset238\fprq2{\*\panose 02020603050405020304}Times New Roman;}
        '''{\f2\fbidi \fmodern\fcharset238\fprq1{\*\panose 02070309020205020404}Courier New;}{\f10\fbidi \fnil\fcharset2\fprq2{\*\panose 05000000000000000000}Wingdings;}{\f34\fbidi \froman\fcharset238\fprq2{\*\panose 02040503050406030204}Cambria Math;} [zbytek řetězce byl zkrácen];.
        '''</summary>
        Friend ReadOnly Property Readme_en() As String
            Get
                Return ResourceManager.GetString("Readme_en", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledá lokalizovaný řetězec podobný {\rtf1\adeflang1025\ansi\ansicpg1250\uc1\adeff31507\deff0\stshfdbch31506\stshfloch44\stshfhich44\stshfbi31507\deflang1029\deflangfe1029\themelang1029\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset238\fprq2{\*\panose 02020603050405020304}Times New Roman;}
        '''{\f2\fbidi \fmodern\fcharset238\fprq1{\*\panose 02070309020205020404}Courier New;}{\f10\fbidi \fnil\fcharset2\fprq2{\*\panose 05000000000000000000}Wingdings;}{\f34\fbidi \froman\fcharset238\fprq2{\*\panose 02040503050406030204}Cambria Math;} [zbytek řetězce byl zkrácen];.
        '''</summary>
        Friend ReadOnly Property readme_pl() As String
            Get
                Return ResourceManager.GetString("readme_pl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledá lokalizovaný řetězec podobný {\rtf1\adeflang1025\ansi\ansicpg1250\uc1\adeff31507\deff0\stshfdbch31506\stshfloch44\stshfhich44\stshfbi31507\deflang1029\deflangfe1029\themelang1029\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset238\fprq2{\*\panose 02020603050405020304}Times New Roman;}
        '''{\f2\fbidi \fmodern\fcharset238\fprq1{\*\panose 02070309020205020404}Courier New;}{\f10\fbidi \fnil\fcharset2\fprq2{\*\panose 05000000000000000000}Wingdings;}{\f34\fbidi \froman\fcharset238\fprq2{\*\panose 02040503050406030204}Cambria Math;} [zbytek řetězce byl zkrácen];.
        '''</summary>
        Friend ReadOnly Property readme_ru() As String
            Get
                Return ResourceManager.GetString("readme_ru", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledá lokalizovaný řetězec podobný {\rtf1\adeflang1025\ansi\ansicpg1250\uc1\adeff31507\deff0\stshfdbch31506\stshfloch44\stshfhich44\stshfbi31507\deflang1029\deflangfe1029\themelang1029\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset238\fprq2{\*\panose 02020603050405020304}Times New Roman;}
        '''{\f2\fbidi \fmodern\fcharset238\fprq1{\*\panose 02070309020205020404}Courier New;}{\f10\fbidi \fnil\fcharset2\fprq2{\*\panose 05000000000000000000}Wingdings;}{\f34\fbidi \froman\fcharset238\fprq2{\*\panose 02040503050406030204}Cambria Math;} [zbytek řetězce byl zkrácen];.
        '''</summary>
        Friend ReadOnly Property readme_uk() As String
            Get
                Return ResourceManager.GetString("readme_uk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ru_flag() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ru_flag", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Icon podobný (Ikona).
        '''</summary>
        Friend ReadOnly Property track2() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("track2", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property uk_flag() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("uk_flag", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
